<?php
     session_start();
     $_SESSION["guru_id"];
     $_SESSION["guru_username"];
     unset($_SESSION["guru_id"]);
     unset($_SESSION["guru_username"]);
     session_unset();
     session_destroy();
     header("location:index.php");
?>